name: CI Build

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths-ignore:
    - '.github/**/*codeql*'
    - '.github/*.yml'
  pull_request:
    paths-ignore:
    - '.github/**/*codeql*'
    - '.github/*.yml'

env:
  LC_ALL: en_US.UTF-8
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.count=3

defaults:
  run:
    shell: bash

jobs:
  JDK_Matrix:
    strategy:
      matrix:
        java: [ '11', '17' ]
        os: [ 'ubuntu-latest' ]
        include:
        - os: 'ubuntu-latest'
          java: '8'
          canonical: ${{ (github.repository == 'osgi/slf4j-osgi') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/release')) && (github.event_name != 'pull_request') }}
    name: JDK${{ matrix.java }} ${{ matrix.os }} ${{ matrix.mavenopts }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Build
      id: build
      continue-on-error: ${{ matrix.experimental }}
      run: |
        ./.github/scripts/build.sh ${{ matrix.mavenopts }}
    - name: Publish
      if: (matrix.canonical && (steps.build.outcome == 'success'))
      run: |
        ./.github/scripts/publish.sh -Possrh
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

